mail_plugins {
  fts = yes
  fts_flatcurve = yes
}

fts flatcurve {
  commit_limit = 500
  min_term_size = 2
  substring_search = no
  rotate_count = 5000
  rotate_time = 5000s
  optimize_limit = 10
}

fts_search_add_missing = yes
