import_environment {
  DOVECOT_DB_HOST = %{env:DOVECOT_DB_HOST | default(localhost)}
  DOVECOT_DB_PORT = %{env:DOVECOT_DB_PORT | default(5432)}
  DOVECOT_DB_NAME = %{env:DOVECOT_DB_NAME | default(mailfallback)}
  DOVECOT_DB_USER = %{env:DOVECOT_DB_USER | default(mailfallback)}
  DOVECOT_DB_PASSWORD = %{env:DOVECOT_DB_PASSWORD | default(mailfallback)}
  DOVECOT_API_KEY = %{env:DOVECOT_API_KEY | default(changeme)}
  DOVECOT_OAUTH2_USERINFO_URL = %{env:DOVECOT_OAUTH2_USERINFO_URL | default(none)}
  MFB_USERDB_URL = %{env:MFB_USERDB_URL | default(http://mailfallback:8000)}
}

auth_mechanisms = plain login oauthbearer xoauth2

sql_driver = pgsql

pgsql %{env:DOVECOT_DB_HOST} {
  parameters {
    port = %{env:DOVECOT_DB_PORT}
    dbname = %{env:DOVECOT_DB_NAME}
    user = %{env:DOVECOT_DB_USER}
    password = %{env:DOVECOT_DB_PASSWORD}
  }
}

oauth2_introspection_url = %{env:DOVECOT_OAUTH2_USERINFO_URL}
oauth2_introspection_mode = auth
oauth2_username_attribute = preferred_username

passdb oauth2 {
  mechanisms_filter = oauthbearer xoauth2
}

passdb sql {
  query = SELECT username, password_hash AS password \
    FROM users \
    WHERE username = '%{user}' AND enabled = true AND migrating = false
}

userdb lua {
  lua_file = /etc/dovecot/conf.d/mfb-lua-userdb.lua
}

passdb_default_password_scheme = BLF-CRYPT  # pragma: allowlist secret
doveadm_password = %{env:DOVECOT_API_KEY}  # pragma: allowlist secret
