"""add email_address to accounts

Revision ID: 3f225361d14c
Revises: f3302dfb5bad
Create Date: 2026-04-28 16:25:50.929092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f225361d14c'
down_revision: Union[str, Sequence[str], None] = 'f3302dfb5bad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('email_address', sa.String(), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'email_address')
    # ### end Alembic commands ###
