hostname: mfb.example.com
webmail:
  enabled: true
  hostname: mail.example.com
tika:
  enabled: true
inlineSecrets:
  app:
    enabled: true
    annotations:
      vaultsync/watch: "secret/data/mailfallback"
    values:
      MAILFALLBACK_DB_PASSWORD: "${vault:secret/data/example#db_password}" # pragma: allowlist secret
      MAILFALLBACK_DOVECOT_API_KEY: "${vault:secret/data/example#api_key}" # pragma: allowlist secret
  roundcube:
    enabled: true
    annotations:
      vaultsync/watch: "secret/data/mailfallback"
    values:
      ROUNDCUBEMAIL_DB_PASSWORD: "${vault:secret/data/example#db_password}" # pragma: allowlist secret
      ROUNDCUBEMAIL_DEFAULT_PORT: "31993"
